export const mainTheme = {
  token: {
    fontFamily: "Outfit, sans-serif",
    colorPrimary: "#FF9815",
  },
  components: {
    Menu: {
      fontSize: 16,
      iconSize: 24,
      itemActiveBg: "#FF981599",
      itemActiveColor: "#8A8D8E",
      itemHoverColor: "#8A8D8E",
      itemColor: "#8A8D8E",
      itemSelectedBg: "#FF9815",
      itemSelectedColor: "#ffffff",
      iconColor: "#8A8D8E",
      subMenuItemBg: "#ffffff11",
    },
    Form: {
      colorError: "#E53935",
    },
    Checkbox: {
      colorPrimary: "#FF9815",
      colorPrimaryHover: "#FF9815",
    },
    Select: {
      colorTextQuaternary: "#3A3A3A",
      colorBgContainer: "rgba(0,0,0,0)",
      fontSize: 18,
      optionSelectedColor: "#ffffff",
      optionSelectedBg: "#FF9815",
      optionActiveBg: "#FF981529",
      optionActiveColor: "#FF9815",
      colorBorder: "#47586E",
      colorBgElevated: "#ffffff",
      selectorBg: "#ffffff",
      colorText: "#47586E",
      colorTextPlaceholder: "#3A3A3A99",
      // activeOutlineColor: "#D3EBE7",
      // activeBorderColor: "#D3EBE7",
      hoverBorderColor: "#D3EBE7",
      colorIcon: "#3A3A3A",
    },
    DatePicker: {
      fontSize: 20,
      colorTextPlaceholder: "#3A3A3A",
      colorBgElevated: "#ffffff",
      colorText: "#47586E",
      colorTextHeading: "#47586EBB",
      colorTextDisabled: "#47586E33",
      colorIcon: "#47586E99",
      colorIconHover: "#47586E",
    },
    timePicker: {
      fontSize: 20,
      colorTextPlaceholder: "#3A3A3A",
      colorBgElevated: "#47586E",
      colorText: "#ffffff",
      colorTextHeading: "#47586EBB",
      colorTextDisabled: "#47586E33",
      colorIcon: "#47586E99",
      colorIconHover: "#47586E",
    },
    Upload: {
      colorTextQuaternary: "#47586E",
      colorFillAlter: "rgba(0,0,0,0)",
      colorBorder: "#47586E",
      colorBorderHover: "#47586E",
      colorText: "#47586E",
      colorIcon: "#47586E",
      actionsColor: "rgba(255,0,0)",
    },
    Table: {
      colorTextQuaternary: "#ffffff",
      colorIcon: "#ffffff",
      headerBg: "#FF9815",
      colorBgContainer: "#FFF0DC",
      colorText: "#111111",
      borderColor: "#ffffff",
      headerColor: "#ffffff",
      fontSize: 18,
      footerColor: "#FDFDFD",
      headerBorderRadius: 0,
      // marginXXS: 4,
      colorLinkActive: "#FDFDFD",
      headerSplitColor: "#ffffff",
    },
    Pagination: {
      colorBgContainer: "#FFFFFF",
      itemActiveBg: "#FF9815",
      itemActiveColor: "rgb(255,255,255)",
      colorPrimary: "rgb(255,255,255)",
      colorPrimaryHover: "rgb(255,255,255)",
      colorText: "#262621",
      colorBgTextHover: "#FF981555",
    },
    Input: {
      colorTextPlaceholder: "#3A3A3A99 ",
      colorIcon: "#3A3A3A",
    },
    Radio: {
      colorPrimary: "#FF9815",
      colorPrimaryHover: "#FF9815",
    },
    Modal: {
      contentBg: "#FFF0DC",
      headerBg: "#FFF0DC",
      colorIcon: "#47586E",
      colorIconHover: "#47586E",
      colorText: "#47586E",
    },
    Rate: {
      starBg: "#ffffff66",
    },
  },
};
